const data = {
  data: {
    shoplink: {
      id: 870975,
      username: 'megyalook',
      pic:
        'https://scontent-sea1-1.xx.fbcdn.net/v/t51.2885-15/131381270_431160258019009_5267438787337586843_n.jpg?_nc_cat=110&ccb=2&_nc_sid=86c713&_nc_ohc=DRw4yl8obggAX94fhTh&_nc_ht=scontent-sea1-1.xx&oh=db63e240af8c8aa106b019c4a1796849&oe=603F174E',
      description: 'colorful paper goods & enamel pins based in Austin, Texas',
      buttonHexColor: '#D3A255',
      featuredData: [
        {
          __typename: 'Product',
          id: 616774,
          externalId: null,
          name: 'Desert Bandana',
          sku: '',
          enabled: true,
          shipping: true,
          currency: 'USD',
          price: 25,
          description:
            'DETAILS:\n\n∙ Dimensions: 21x21 inches \n∙ Silk/cotton blend ',
          smallUrl:
            'https://media-assets.planoly.com/photo/product/small?url=MmQ4YTJlNmEtODk1MC00ZWE2LThlNWQtOTZmNDhmMmY3YjAyLnBuZw==',
          posterUrl:
            'https://media-assets.planoly.com/photo/product/poster?url=MmQ4YTJlNmEtODk1MC00ZWE2LThlNWQtOTZmNDhmMmY3YjAyLnBuZw==',
          thumbnailUrl:
            'https://media-assets.planoly.com/photo/product/thumbnail?url=MmQ4YTJlNmEtODk1MC00ZWE2LThlNWQtOTZmNDhmMmY3YjAyLnBuZw==',
          buyUrl: 'https://sellit.bio/yymdj',
          slug: '/megyalook/616774-desert-bandana/buy',
          url: '',
          canCheckout: true,
          isExternal: false,
          taggedCount: 2,
          x: null,
          y: null,
          sortOrder: null,
          quantity: 1,
          vendor: 'planoly',
          digitalUrl: null,
          isDigitalDownload: false,
          allowDigitalExpiry: false,
        },
        {
          __typename: 'Product',
          id: 594046,
          externalId: null,
          name: 'I Cry A lot Pin ',
          sku: '',
          enabled: true,
          shipping: true,
          currency: 'USD',
          price: 10,
          description:
            'For all my empaths out there, I feel you. I hope this pin empowers you to wear your feelings on your sleeve & cry wherever you want to. \n\nDETAILS:\n∙ 1" hard enamel pin\n∙ Yellow single rubber backing \n∙ Shiny gold finish',
          smallUrl:
            'https://media-assets.planoly.com/photo/product/thumbnail?url=YzEzNzZmMjItNjAyYS00ZmJmLTgxMjctNDgxYTBjN2E1NTI0LmpwZWc=',
          posterUrl:
            'https://media-assets.planoly.com/photo/product/thumbnail?url=YzEzNzZmMjItNjAyYS00ZmJmLTgxMjctNDgxYTBjN2E1NTI0LmpwZWc=',
          thumbnailUrl:
            'https://media-assets.planoly.com/photo/product/thumbnail?url=YzEzNzZmMjItNjAyYS00ZmJmLTgxMjctNDgxYTBjN2E1NTI0LmpwZWc=',
          buyUrl: 'https://sellit.bio/xpd3k',
          slug: '/megyalook/594046-i-cry-a-lot-pin/buy',
          url: '',
          canCheckout: true,
          isExternal: false,
          taggedCount: 3,
          x: null,
          y: null,
          sortOrder: null,
          quantity: 1,
          vendor: 'planoly',
          digitalUrl: null,
          isDigitalDownload: false,
          allowDigitalExpiry: false,
        },
        {
          __typename: 'Product',
          id: 594130,
          externalId: null,
          name: "Mom's Grocery Tote",
          sku: '',
          enabled: false,
          shipping: true,
          currency: 'USD',
          price: 25,
          description:
            'You’re totes going to be the cutest shopper wherever you go.\n\nDETAILS: \nDimensions: 15.5"l x 13"w; 7" deep\nWide bottom, perfect for groceries & large items\nPrint on one side \nMade of 100% natural material\n100% Cotton Twill',
          smallUrl:
            'https://media-assets.planoly.com/photo/product/small?url=MTkxMjViMTYtYTA0NC00MTFhLTlhY2ItODkzNjgwNWY1OWE2LmpwZWc=',
          posterUrl:
            'https://media-assets.planoly.com/photo/product/poster?url=MTkxMjViMTYtYTA0NC00MTFhLTlhY2ItODkzNjgwNWY1OWE2LmpwZWc=',
          thumbnailUrl:
            'https://media-assets.planoly.com/photo/product/thumbnail?url=MTkxMjViMTYtYTA0NC00MTFhLTlhY2ItODkzNjgwNWY1OWE2LmpwZWc=',
          buyUrl: 'https://sellit.bio/plqqy',
          slug: '/megyalook/594130-moms-grocery-tote/buy',
          url: '',
          canCheckout: true,
          isExternal: false,
          taggedCount: 1,
          x: null,
          y: null,
          sortOrder: null,
          quantity: 1,
          vendor: 'planoly',
          digitalUrl: null,
          isDigitalDownload: false,
          allowDigitalExpiry: false,
        },
      ],
      showFeatured: true,
      showProductsTab: true,
      showPostsTab: true,
      isPublic: true,
      isShoplink: true,
      links: [
        { title: 'SHOP', url: 'http://www.megyalook.com/shop' },
        {
          title: 'HEALING THROUGH ART',
          url: 'https://blog.planoly.com/megan-martinez-megyalook-interview',
        },
      ],
      stripeAccount: { id: 63 },
      ecommerceAccount: null,
    },
  },
}
